[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    lvgl/lvgl@8.3.11

board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv

build_flags =
    -std=gnu++20
    -D LV_CONF_INCLUDE_SIMPLE
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D ESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED
    -D BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7
    -I .
    -I src

build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17